### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by ghost** [dylanaraps/eiwd_old#1]
Hi dylan,

Im getting below error when trying to make.

```
make[1]: *** No rule to make target 'ell/util.c', needed by 'ell/util.lo'.  Stop.
make: *** [Makefile:1220: all] Error 2
```
Ive install ell and ell-devel my voidlinux x86-64 laptop box.

I did have to install libtdl-devel and the autoreconf -i to get to this error and unsure how to proceed further?

V

**Comment by dylanaraps** [comment]
You need to use `--enable-external-ell` if using the ELL library externally. If you'd like to use the bundled library, stick to the GitHub releases here: https://github.com/dylanaraps/eiwd/releases

**Comment by ghost** [comment]
Ok thanks

**Comment by ghost** [comment]
hi again, i managed to build this ok. problem im having on voidlinux is there is no /usr/libexec/iwd. Im not sure how to get the daemon to run so im borrowing off the void runit srcpkg run config but that is a fail obviously.
https://github.com/void-linux/void-packages/blob/master/srcpkgs/iwd/files/iwd/run

I probably just dont understand how it works without dbus on voidlinux.

**Comment by dylanaraps** [comment]
`eiwd` installs `iwd` to `/usr/bin` (or wherever your `bin` directory is).
